### ISSUE TITLE
Endless leaderboards button not work (Linux)

### ISSUE THREAD

**Issue by Longer** [dukope/BugsPlease#24] opened 2014-02-03 02:26 UTC
If click on button show message - "Can't open default browser"

**Comment by Tailszefox** [comment] 2014-02-03 08:07
Since it's working for me, here's a suggestion: assuming you're using a Debian-based distribution (Ubuntu or Mint qualify), can you give the output of `update-alternatives --display x-www-browser` ? It should show the default browser you currently have. If it's pointing to something wrong or non-existent, try `sudo update-alternatives --config x-www-browser` . This should set the default browser correctly, and assuming that's how the game gets the value, it should fix it.

**Comment by Longer** [comment] 2014-02-03 08:18
I use Gentoo (not have update-alternatives) with xfce and other programs open my default browser.

PS maybe better use for open leaderboards `xdg-open` (or  analogue)?

OR open use Steam browser

**Comment by dukope** [comment] 2014-02-03 10:48
As far as I can tell, this is the code it's currently using on Linux:

``` C++
    bool LaunchBrowser (const char *inUtf8URL) {

        string url = inUtf8URL;
        string command = "xdg-open " + url;

        int result = system(command.c_str());

        return (result != -1);

    }
```

Where url = "http://steamcommunity.com/stats/PapersPlease/leaderboards"

@Longer, can you check if this works from the command line?

**Comment by Longer** [comment] 2014-02-03 11:08
It work in command line.

PS But better use steam browser for it (many games use him for show steam leaderboards and other web-content). And it fix little bug with _unfullscreen_, when I click it button (if use steam browser leaderboards show in Shift+Tab (auto-activate)) + it crossplatform method (one function for all OS).

**Comment by Tailszefox** [comment] 2014-02-03 16:17
The issue I can see is that the game is also available outside of Steam, DRM-free. So even if that was done, it would only solve the issue for Steam builds, which isn't really fixing it.

It's weird that the command works on the command line but not when launched through the game. Is Steam run by a different user or in a different environment that has the wrong browser assigned?

**Comment by dukope** [comment] 2014-02-03 16:28
Steam does run in a different environment, which I guess may be messing things up.

I could actually use the Steam browser for the leaderboards. The non-Steam version of the game doesn't support leaderboards and doesn't have this button. The problem is that I can't find how to actually open the Steam browser to the leaderboards :) Their SDK documentation is pretty hard to search.

I'm probably going to waive this issue for now. Using xdg-open seems like a reasonable move and the feature isn't so critical that I want to spend too much time on fixing it.

**Comment by Tailszefox** [comment] 2014-02-03 16:49
Ah, my bad, that's what I get from only playing the Steam version. It's weird though that it is working for me, if Steam does run a different environment no matter what. I suppose some variables aren't "transferred" the same way depending on your system or configuration.

**Comment by dukope** [comment] 2014-02-04 13:28
I'm gonna waive this for now.

**Closed as completed by dukope** 2014-02-04 13:28 UTC
