### ISSUE TITLE
Audio transcipt

### ISSUE THREAD

**Issue by Longer** [dukope/BugsPlease#21] opened 2014-02-02 10:50 UTC
If dialogue with man >1 page and I scroll 2 (or more) page, with next man me need scroll back, so as I not see dialogue in "audio transcript".

![2014-02-02_00001](https://f.cloud.github.com/assets/103578/2060075/b94ac64a-8bf7-11e3-8578-dcb47c423ab1.jpg)
![2014-02-02_00002](https://f.cloud.github.com/assets/103578/2060076/bda9f3f0-8bf7-11e3-99b2-5fe60070e62c.jpg)

**Comment by ErdmannOle** [comment] 2014-02-02 17:10
Yes, this illustrates the bug I was describing a little earlier. https://github.com/dukope/BugsPlease/issues/20#issuecomment-33896136

**Comment by ErdmannOle** [comment] 2014-02-02 21:16
A small addition: since the issue with overlapping text often occurs in the German version I suppose it would be a great solution to make the audio transcript scrollable if there's a longer conversation. That way there would be no overlapping text and the bug with staying on the second page would be solved as well. I altered the transcript in the picture below, so this is what it could look like. :)

![audio transcript scroll](https://f.cloud.github.com/assets/6563832/2061375/85c65918-8c4e-11e3-8233-a1e1d91bd869.PNG)

**Comment by dukope** [comment] 2014-02-03 10:56
@ErdmannOle, that's a good idea but there's currently no facility in the game for scrolling text like this. The issue is minor enough that I'm inclined to waive it.

I'll take a look at reseting to the first page after the immigrant leaves to fix @Longer's issue

**Comment by dukope** [comment] 2014-02-04 13:25
@Longer's issue is fixed in 1.1.57

**Closed as completed by dukope** 2014-02-04 13:25 UTC
Labels: fixed-in-next
